In [1]:
import torch



In [2]:
taxonomy_graph_path = "/NAS/luyq/AMP_datasets/taxonomy_graph.pt"
taxonomy_graph = torch.load(taxonomy_graph_path)

/tmp/ipykernel_10385/4028549667.py:2: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  taxonomy_graph = torch.load(taxonomy_graph_path)


In [3]:
taxonomy_graph.keys()

dict_keys(['node2idx', 'idx2name', 'idx2level', 'idx2taxid', 'edge_index', 'edge_type', 'init_features', 'species2nodeid', 'species_taxid2nodeid', 'ancestors_per_species', 'species_names', 'levels', 'num_edge_types'])

In [5]:
taxonomy_graph['node2idx']

{'2': 0,
 '1783272': 1,
 '544448': 2,
 '31969': 3,
 '186329': 4,
 '2146': 5,
 '2147': 6,
 '2148': 7,
 '3379134': 8,
 '1224': 9,
 '28216': 10,
 '80840': 11,
 '506': 12,
 '222': 13,
 '85698': 14,
 '1236': 15,
 '2887326': 16,
 '468': 17,
 '469': 18,
 '470': 19,
 '202950': 20,
 '471': 21,
 '40214': 22,
 '40215': 23,
 '28090': 24,
 '135625': 25,
 '712': 26,
 '713': 27,
 '715': 28,
 '201174': 29,
 '1760': 30,
 '2037': 31,
 '2049': 32,
 '1654': 33,
 '1659': 34,
 '1655': 35,
 '1656': 36,
 '1239': 37,
 '91061': 38,
 '186826': 39,
 '186827': 40,
 '1375': 41,
 '1377': 42,
 '135624': 43,
 '84642': 44,
 '642': 45,
 '648': 46,
 '644': 47,
 '645': 48,
 '646': 49,
 '654': 50,
 '416916': 51,
 '714': 52,
 '28211': 53,
 '356': 54,
 '82115': 55,
 '357': 56,
 '358': 57,
 '507': 58,
 '511': 59,
 '1385': 60,
 '186823': 61,
 '29330': 62,
 '1450': 63,
 '186817': 64,
 '2675234': 65,
 '1445': 66,
 '2759': 67,
 '4751': 68,
 '4890': 69,
 '147541': 70,
 '92860': 71,
 '28556': 72,
 '5598': 73,
 '5599': 74,
 '29911':

In [28]:
taxonomy_graph['idx2name'][8]

'Pseudomonadati'

In [10]:
'Fungi' in taxonomy_graph['idx2name']

True

In [ ]:
taxonomy_graph['idx2level'][taxonomy_graph['idx2name'].index('Fungi')] # Fungi应该属于kingdom

tensor(1)

In [18]:
taxonomy_graph['edge_index']

tensor([[125, 126, 588,  ..., 687, 653, 656],
        [126, 125, 594,  ..., 675, 656, 653]])

In [20]:
taxonomy_graph['edge_type'].unique()

tensor([ 1, 10, 19, 20, 28, 37, 38, 46, 55])

In [22]:
taxonomy_graph['species2nodeid']

{'Acholeplasma laidlawii': 7,
 'Achromobacter xylosoxidans': 14,
 'Acinetobacter baumannii': 19,
 'Acinetobacter baylyi': 20,
 'Acinetobacter calcoaceticus': 21,
 'Acinetobacter johnsonii': 22,
 'Acinetobacter junii': 23,
 'Acinetobacter lwoffii': 24,
 'Actinobacillus pleuropneumoniae': 28,
 'Actinomyces israelii': 34,
 'Actinomyces naeslundii': 35,
 'Actinomyces viscosus': 36,
 'Aerococcus viridans': 42,
 'Aeromonas caviae': 46,
 'Aeromonas hydrophila': 47,
 'Aeromonas salmonicida': 48,
 'Aeromonas sobria': 49,
 'Aeromonas veronii': 50,
 'Aggregatibacter actinomycetemcomitans': 52,
 'Agrobacterium tumefaciens': 57,
 'Alcaligenes faecalis': 59,
 'Alicyclobacillus acidoterrestris': 63,
 'Alkalihalobacillus alcalophilus': 66,
 'Alternaria alternata': 74,
 'Alternaria brassicae': 75,
 'Alternaria brassicicola': 76,
 'Alternaria dauci': 77,
 'Alternaria longipes': 78,
 'Arthrobacter globiformis': 82,
 'Ascochyta pisi': 85,
 'Aspergillus awamori': 90,
 'Aspergillus brasiliensis': 91,
 'Aspe

In [23]:
taxonomy_graph['species_taxid2nodeid']

{2148: 7,
 85698: 14,
 470: 19,
 202950: 20,
 471: 21,
 40214: 22,
 40215: 23,
 28090: 24,
 715: 28,
 1659: 34,
 1655: 35,
 1656: 36,
 1377: 42,
 648: 46,
 644: 47,
 645: 48,
 646: 49,
 654: 50,
 714: 52,
 358: 57,
 511: 59,
 1450: 63,
 1445: 66,
 5599: 74,
 29911: 75,
 29001: 76,
 48095: 77,
 160389: 78,
 1665: 82,
 749586: 85,
 105351: 90,
 319629: 91,
 5057: 92,
 5059: 93,
 746128: 94,
 162425: 95,
 5061: 96,
 40380: 97,
 5062: 98,
 5067: 99,
 75750: 100,
 33178: 101,
 170004: 106,
 5580: 110,
 61296: 111,
 354: 115,
 1390: 117,
 1452: 118,
 1396: 119,
 1402: 120,
 1405: 121,
 1408: 122,
 1423: 123,
 1428: 124,
 817: 130,
 818: 131,
 109871: 136,
 176275: 141,
 47735: 143,
 1680: 147,
 1685: 148,
 216816: 149,
 518: 151,
 40559: 156,
 1849799: 157,
 55214: 161,
 235: 164,
 29461: 165,
 95486: 168,
 292: 169,
 87883: 170,
 95485: 171,
 57975: 172,
 195: 178,
 197: 179,
 201: 180,
 5476: 185,
 5477: 189,
 42374: 190,
 5480: 191,
 5482: 192,
 5486: 193,
 2748: 196,
 2751: 197,
 38033: 

In [24]:
taxonomy_graph['ancestors_per_species']


tensor([[  0,   1,   2,  ...,   5,   6,   7],
        [  0,   8,   9,  ...,  12,  13,  14],
        [  0,   8,   9,  ...,  17,  18,  19],
        ...,
        [  0,   8,   9,  ..., 562, 701, 703],
        [  0,   8,   9,  ..., 562, 701, 704],
        [  0,   8,   9,  ..., 706, 707, 708]])

In [25]:
len(taxonomy_graph['ancestors_per_species'])

366

In [27]:
taxonomy_graph['species_names']

['Acholeplasma laidlawii',
 'Achromobacter xylosoxidans',
 'Acinetobacter baumannii',
 'Acinetobacter baylyi',
 'Acinetobacter calcoaceticus',
 'Acinetobacter johnsonii',
 'Acinetobacter junii',
 'Acinetobacter lwoffii',
 'Actinobacillus pleuropneumoniae',
 'Actinomyces israelii',
 'Actinomyces naeslundii',
 'Actinomyces viscosus',
 'Aerococcus viridans',
 'Aeromonas caviae',
 'Aeromonas hydrophila',
 'Aeromonas salmonicida',
 'Aeromonas sobria',
 'Aeromonas veronii',
 'Aggregatibacter actinomycetemcomitans',
 'Agrobacterium tumefaciens',
 'Alcaligenes faecalis',
 'Alicyclobacillus acidoterrestris',
 'Alkalihalobacillus alcalophilus',
 'Alternaria alternata',
 'Alternaria brassicae',
 'Alternaria brassicicola',
 'Alternaria dauci',
 'Alternaria longipes',
 'Arthrobacter globiformis',
 'Ascochyta pisi',
 'Aspergillus awamori',
 'Aspergillus brasiliensis',
 'Aspergillus clavatus',
 'Aspergillus flavus',
 'Aspergillus fumigatus',
 'Aspergillus nidulans',
 'Aspergillus niger',
 'Aspergillu